import 'transaction.dart';

class Member {
  final String id;
  final String name;
  final String contact; // phone number
  final String email;
  final DateTime? dob;
  final DateTime? joinedDate;
  final double totalBought;
  final double totalSold;
  final String status;
  final List<Transaction> transactions;

  Member({
    required this.id,
    required this.name,
    required this.contact,
    required this.email,
    required this.dob,
    required this.joinedDate,
    required this.totalBought,
    required this.totalSold,
    this.status = 'active',
    required this.transactions,
  });

  factory Member.fromJson(Map<String, dynamic> json) {
    return Member(
      id: json['_id']?.toString() ?? json['id']?.toString() ?? '',
      name: json['name'] as String? ?? '',
      contact: json['mobile'] as String? ?? '',
      email: json['email'] as String? ?? '',
      dob: json['dob'] != null
          ? DateTime.tryParse(json['dob'] as String)
          : null,
      joinedDate: json['registeredAt'] != null
          ? DateTime.tryParse(json['registeredAt'] as String)
          : null,
      totalBought: (json['totalBuyAmount'] as num?)?.toDouble() ?? 0.0,
      totalSold: (json['totalSellAmount'] as num?)?.toDouble() ?? 0.0,
      status: json['status'] as String? ?? 'active',
      transactions:
          [], // Transactions are not returned in list view from NF backend for performance
    );
  }

  Map<String, dynamic> toJson() => {
    'id':
        id, // Map back to what backend expects if we send full object, though usually we send specific fields
    'name': name,
    'mobile': contact,
    'email': email,
    'dob': dob?.toIso8601String(),
    'registeredAt': joinedDate?.toIso8601String(),
    'status': status,
    'nic': 'N/A', // Placeholder if missing
    'address': 'N/A', // Placeholder
    'memberCode': '', // Generated by backend
  };
}
