import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../services/employee_service.dart';

class BulkEmployeeRow {
  final TextEditingController fullName = TextEditingController();
  final TextEditingController email = TextEditingController();
  final TextEditingController phone = TextEditingController();
  final TextEditingController password = TextEditingController();
  final TextEditingController salary = TextEditingController();
  final TextEditingController targetAmount = TextEditingController(text: '0.0');
  final TextEditingController assignedArea = TextEditingController();
  final TextEditingController bankName = TextEditingController();
  final TextEditingController bankBranch = TextEditingController();
  final TextEditingController accountNo = TextEditingController();
  final TextEditingController accountHolder = TextEditingController();
  final TextEditingController nic = TextEditingController();
  final TextEditingController address = TextEditingController();

  String role = 'Branch Manager';
  String branch = 'Kalmunai'; // Default or first available
  DateTime dob = DateTime(1990);
  DateTime joinedDate = DateTime.now();

  void dispose() {
    fullName.dispose();
    email.dispose();
    phone.dispose();
    password.dispose();
    salary.dispose();
    targetAmount.dispose();
    assignedArea.dispose();
    bankName.dispose();
    bankBranch.dispose();
    accountNo.dispose();
    accountHolder.dispose();
    nic.dispose();
    address.dispose();
  }
}

class BulkEntryDialog extends StatefulWidget {
  final VoidCallback onSaveComplete;

  const BulkEntryDialog({super.key, required this.onSaveComplete});

  @override
  State<BulkEntryDialog> createState() => _BulkEntryDialogState();
}

class _BulkEntryDialogState extends State<BulkEntryDialog> {
  List<BulkEmployeeRow> rows = [];
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    _addRow(); // Start with one row
  }

  @override
  void dispose() {
    for (var row in rows) {
      row.dispose();
    }
    super.dispose();
  }

  void _addRow() {
    setState(() {
      rows.add(BulkEmployeeRow());
    });
  }

  void _removeRow(int index) {
    if (rows.length > 1) {
      setState(() {
        rows[index].dispose();
        rows.removeAt(index);
      });
    }
  }

  Future<void> _saveAll() async {
    setState(() => _isSaving = true);
    int successCount = 0;
    List<String> errors = [];

    for (int i = 0; i < rows.length; i++) {
      var row = rows[i];

      // Basic Validation
      if (row.fullName.text.isEmpty ||
          row.email.text.isEmpty ||
          row.password.text.isEmpty) {
        errors.add('Row ${i + 1}: Missing Name, Email, or Password');
        continue;
      }

      try {
        final employee = Employee(
          id: '',
          userId: '', // Generated by backend
          fullName: row.fullName.text,
          email: row.email.text,
          phone: row.phone.text,
          role: row.role,
          branchName: row.branch,
          branchId:
              'default', // Need to map this if possible, or backend handles it
          status: 'active',
          joinedDate: row.joinedDate,
          salary: double.tryParse(row.salary.text) ?? 0.0,
          dob: row.dob,

          // Password
          password: row.password.text,

          // Field Visitor
          targetAmount: double.tryParse(row.targetAmount.text) ?? 0.0,
          assignedArea: row.assignedArea.text,

          // Bank
          bankName: row.bankName.text,
          bankBranch: row.bankBranch.text,
          accountNo: row.accountNo.text,
          accountHolder: row.accountHolder.text,

          // New Fields
          nic: row.nic.text,
          postalAddress: row.address.text,
          permanentAddress: row.address.text,
          education: 'N/A', // Default
          civilStatus: 'Single', // Default
        );

        await EmployeeService.addEmployee(employee);
        successCount++;
      } catch (e) {
        errors.add('Row ${i + 1}: Error - $e');
      }
    }

    setState(() => _isSaving = false);

    // Show summary
    if (mounted) {
      showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
          title: const Text('Bulk Entry Summary'),
          content: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text('Successfully added: $successCount'),
                if (errors.isNotEmpty) ...[
                  const SizedBox(height: 10),
                  const Text(
                    'Errors:',
                    style: TextStyle(
                      color: Colors.red,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  ...errors.map(
                    (e) => Text(
                      e,
                      style: const TextStyle(color: Colors.red, fontSize: 12),
                    ),
                  ),
                ],
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.pop(ctx); // Close summary
                if (successCount > 0) {
                  widget.onSaveComplete(); // Refresh parent
                  Navigator.pop(context); // Close bulk dialog
                }
              },
              child: const Text('OK'),
            ),
          ],
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      insetPadding: const EdgeInsets.all(10),
      child: Container(
        width: double.infinity,
        height: double.infinity,
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'Bulk Employee Entry',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
                IconButton(
                  icon: const Icon(Icons.close),
                  onPressed: () => Navigator.pop(context),
                ),
              ],
            ),
            Expanded(
              child: SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: DataTable(
                    columnSpacing: 20,
                    columns: const [
                      DataColumn(label: Text('Full Name *')),
                      DataColumn(label: Text('Email *')),
                      DataColumn(label: Text('Phone')),
                      DataColumn(label: Text('Password *')),
                      DataColumn(label: Text('Role')),
                      DataColumn(label: Text('Branch')),
                      DataColumn(label: Text('NIC')),
                      DataColumn(label: Text('Address')),
                      DataColumn(label: Text('Salary')),
                      DataColumn(label: Text('Target (FV)')),
                      DataColumn(label: Text('Area (FV)')),
                      DataColumn(label: Text('DOB')),
                      DataColumn(label: Text('Joined Date')),
                      DataColumn(label: Text('Action')),
                    ],
                    rows: List.generate(rows.length, (index) {
                      final row = rows[index];
                      return DataRow(
                        cells: [
                          DataCell(
                            SizedBox(
                              width: 150,
                              child: TextField(
                                controller: row.fullName,
                                decoration: const InputDecoration(
                                  hintText: 'Name',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 150,
                              child: TextField(
                                controller: row.email,
                                decoration: const InputDecoration(
                                  hintText: 'Email',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 120,
                              child: TextField(
                                controller: row.phone,
                                decoration: const InputDecoration(
                                  hintText: 'Phone',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 120,
                              child: TextField(
                                controller: row.password,
                                obscureText: false,
                                decoration: const InputDecoration(
                                  hintText: 'Pass',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            DropdownButton<String>(
                              value: row.role,
                              items: EmployeeService.roles
                                  .map(
                                    (r) => DropdownMenuItem(
                                      value: r,
                                      child: Text(r),
                                    ),
                                  )
                                  .toList(),
                              onChanged: (v) => setState(() => row.role = v!),
                            ),
                          ),
                          DataCell(
                            DropdownButton<String>(
                              value: row.branch,
                              items: EmployeeService.branches
                                  .map(
                                    (b) => DropdownMenuItem(
                                      value: b,
                                      child: Text(b),
                                    ),
                                  )
                                  .toList(),
                              onChanged: (v) => setState(() => row.branch = v!),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 120,
                              child: TextField(
                                controller: row.nic,
                                decoration: const InputDecoration(
                                  hintText: 'NIC',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 150,
                              child: TextField(
                                controller: row.address,
                                decoration: const InputDecoration(
                                  hintText: 'Address',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 100,
                              child: TextField(
                                controller: row.salary,
                                keyboardType: TextInputType.number,
                                decoration: const InputDecoration(
                                  hintText: '0.0',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 100,
                              child: TextField(
                                controller: row.targetAmount,
                                keyboardType: TextInputType.number,
                                decoration: const InputDecoration(
                                  hintText: '0.0',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            SizedBox(
                              width: 120,
                              child: TextField(
                                controller: row.assignedArea,
                                decoration: const InputDecoration(
                                  hintText: 'Area',
                                ),
                              ),
                            ),
                          ),
                          DataCell(
                            TextButton(
                              onPressed: () async {
                                final d = await showDatePicker(
                                  context: context,
                                  initialDate: row.dob,
                                  firstDate: DateTime(1960),
                                  lastDate: DateTime.now(),
                                );
                                if (d != null) {
                                  setState(() => row.dob = d);
                                }
                              },
                              child: Text(
                                DateFormat('yyyy-MM-dd').format(row.dob),
                              ),
                            ),
                          ),
                          DataCell(
                            TextButton(
                              onPressed: () async {
                                final d = await showDatePicker(
                                  context: context,
                                  initialDate: row.joinedDate,
                                  firstDate: DateTime(2000),
                                  lastDate: DateTime.now(),
                                );
                                if (d != null) {
                                  setState(() => row.joinedDate = d);
                                }
                              },
                              child: Text(
                                DateFormat('yyyy-MM-dd').format(row.joinedDate),
                              ),
                            ),
                          ),
                          DataCell(
                            IconButton(
                              icon: const Icon(Icons.delete, color: Colors.red),
                              onPressed: () => _removeRow(index),
                            ),
                          ),
                        ],
                      );
                    }),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 10),
            Row(
              children: [
                ElevatedButton.icon(
                  onPressed: _addRow,
                  icon: const Icon(Icons.add),
                  label: const Text('Add Row'),
                ),
                const Spacer(),
                ElevatedButton(
                  onPressed: _isSaving ? null : _saveAll,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.green,
                  ),
                  child: _isSaving
                      ? const CircularProgressIndicator(color: Colors.white)
                      : const Text(
                          'Save All Employees',
                          style: TextStyle(color: Colors.white),
                        ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
