const axios = require('axios');

async function addAnalyzer() {
    try {
        console.log('Attempting to register Analyzer...');
        const response = await axios.post('http://localhost:3001/api/auth/register/analyzer', {
            fullName: 'Hussain Fathima Safna',
            email: 'nfplantation31@gmail.com',
            phone: '0763249033',
            password: 'Safna@31',
            nic: '200159102176'
            // userId will be auto-generated by backend (AZ...)
        });

        console.log('Response Status:', response.status);
        console.log('Response Data:', response.data);
    } catch (error) {
        if (error.response) {
            console.error('Error Response:', error.response.status, error.response.data);
        } else {
            console.error('Error:', error.message);
        }
    }
}

addAnalyzer();
